name: new_zhic_tool
description: "A new zhic tool."
version: 2.0.1

environment:
  sdk: ^3.13.2
dependencies:
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^3.1.0+7447
  m3e_core: ^1.1.2
  material_ui: ^1.1.0
  dynamic_color: ^2.1.0
  share_plus: ^13.3.0
  fluttertoast: ^10.0.0
  flutter_inappwebview: ^6.2.0-beta.3
  shared_preferences: ^2.5.5
  flutter_riverpod: ^3.4.2
  http: ^1.6.0
  flutter_confetti: ^0.9.2
  html: ^0.15.7
  path_provider: ^2.1.6
  mesh: ^0.5.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^10.2.1
  file_picker: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/icon.png

flutter_launcher_icons:
    android: true
    image_path: "assets/images/icon.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/icon.png"

